[package]
name = "myfirst"
version = "0.1.0"
authors = ["dalongrong <1141591465@qq.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "myfirst"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
